#!/bin/bash
if [[ $(git branch --show-current) != element-release ]]; then
    echo "Must be on release branch" >&2
    exit 1
fi

if [[ -n $(git pull --dry-run) ]]; then
    echo "Release branch is not up to date" >&2
    exit 2
fi

VERNUM=$(jq -r .version package.json)
read -p "Publish version $VERNUM? (y/N)> " ANSWER
if [[ $ANSWER == y ]]; then
    yarn publish --new-version $VERNUM --access public --verbose
fi
